FROM node:16-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy source files
COPY . .

# Run Tailwind in watch mode
CMD ["npm", "run", "watch:css"]
