server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Redirecciona /admin.html a /admin
    location = /admin.html {
        return 301 /admin;
    }

    # Muestra /admin como /admin.html
    location = /admin {
        rewrite ^/admin$ /admin.html break;
    }

    # Ubicacion predefinida 
    location / {
        try_files $uri $uri/ =404;
    }
}
